### ISSUE TITLE
关于搭建好网站打不开问题

### ISSUE THREAD

**Issue by KooKang** [iCloudZA/CloudZA_API#2]
作者大大辛苦！我想问问这是什么问题？打开网站首页和安装页面出现404页面。
对了我用的是虚拟机，Linux系统，版本CentOS7

**Comment by iCloudZA** [comment]
> 作者大大辛苦！我想问问这是什么问题？打开网站首页和安装页面出现404页面。
> 对了我用的是虚拟机，Linux系统，版本CentOS7

@KooKang  **白天下午1点**之后加我**QQ2922619853** 我应该能远程帮助你解决这个问题

**Comment by eurasia-admin** [comment]
作者大大 QQ搜不到了 怎么联系您

**Comment by KooKang** [comment]
你好，请问遇到什么问题？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月25日(周五) 下午2:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [iCloudZA/CloudZA_API] 关于搭建好网站打不开问题 (Issue #2)




 
作者大大 QQ搜不到了 怎么联系您
 
&mdash;

**Comment by iCloudZA** [comment]
> 你好，请问遇到什么问题？
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2023年8月25日(周五) 下午2:19
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [iCloudZA/CloudZA_API] 关于搭建好网站打不开问题 (Issue #2)
> 
> 
> 
> 
>  
> 作者大大 QQ搜不到了 怎么联系您
>  
> &mdash;
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

？

**Comment by iCloudZA** [comment]
> 作者大大 QQ搜不到了 怎么联系您

微信 qwqkis
