### ISSUE TITLE
安装的时候会报错

### ISSUE THREAD

**Issue by Dick-Williams** [iCloudZA/CloudZA_API#3]
直接访问域名会提示数据库账号密码错误，访问域名/install进行安装，填写所有信息之后点击安装就会报错。
PHP8，数据库5.6，centos
![Screenshot_20230208_224544_com android chrome](https://user-images.githubusercontent.com/83115890/217678085-f5e14332-f102-4638-ae89-dc2766c0d1c7.jpg)
![Screenshot_20230209_074834_com android chrome](https://user-images.githubusercontent.com/83115890/217678092-095ea73b-4e17-451b-a3c8-21480ace5f0a.jpg)

**Comment by iCloudZA** [comment]
联系QQ2922619853
