### ISSUE TITLE
关于php的扩展

### ISSUE THREAD

**Issue by jinghuashang** [iCloudZA/CloudZA_API#6]
请问这个api的php扩展有哪些？
我采用1panel部署的时候出现mysql不支持
![报错](https://jinghuashang.cn/down/d/%E5%A4%96%E9%83%A8%E5%AD%98%E5%82%A8/%E8%8A%82%E7%82%B91/%E5%9B%BE%E5%BA%8A/444444.png)

**Comment by iCloudZA** [comment]
已经不在维护，新的api系统正在开发中



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月26日(周五) 中午12:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [iCloudZA/CloudZA_API] 关于php的扩展 (Issue #6)




 
请问这个api的php扩展有哪些？
 我采用1panel部署的时候出现mysql不支持
 !(报错)[https://wxtpl-my.sharepoint.com/personal/jinghuashang_wxtpl_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=600ebc7c-70eb-4460-b5c1-686d7aead287&amp;Translate=false&amp;tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvd3h0cGwtbXkuc2hhcmVwb2ludC5jb21ANDk0NmZiNTYtYTYyYS00YjFhLTg1ZDQtNDVmYWFiNTQxMjY0IiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTcwNjI0NTA2NCIsImV4cCI6IjE3MDYyNDg2NjQiLCJlbmRwb2ludHVybCI6InNXczN1UnE2ZXRFbWlSd3BqZDQwS1dEaGI3dFd1QUtuQ0N2R3h6TmcrdUU9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNjMiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6InF2SGJrRGd4bTAyNkpKQXdmK3Q5OVE9PSIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJNMlJoTldFM1kySXRZamRqTnkwME5qSXpMVGcxTnpRdE9EYzVaVGczT1RBMVlUTTAiLCJhcHBfZGlzcGxheW5hbWUiOiJBbGlzdCIsImdpdmVuX25hbWUiOiJCbGFja0JlcnJ5IiwiZmFtaWx5X25hbWUiOiJNaWFyZ2UiLCJzaWduaW5fc3RhdGUiOiJbXCJrbXNpXCJdIiwiYXBwaWQiOiIwYTI5OTFhMy0xNjc0LTQzMzQtODU2MS02NzFjYzczNDk5NjAiLCJ0aWQiOiI0OTQ2ZmI1Ni1hNjJhLTRiMWEtODVkNC00NWZhYWI1NDEyNjQiLCJ1cG4iOiJqaW5naHVhc2hhbmdAd3h0cGwub25taWNyb3NvZnQuY29tIiwicHVpZCI6IjEwMDMyMDAzMEI3MzZFOEMiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMzBiNzM2ZThjQGxpdmUuY29tIiwic2NwIjoiYWxsZmlsZXMud3JpdGUiLCJ0dCI6IjIiLCJpcGFkZHIiOiIyMC4xOTAuMTQ0LjE2OSJ9.pj6-4iO4oFCb_BSYQ_zMOzEwDg87wK0iXSRyS0dbG2M&amp;ApiVersion=2.0]
