### ISSUE TITLE
如何配置 Api接口调用次数

### ISSUE THREAD

**Issue by kxzjoker** [iCloudZA/CloudZA_API#7]
如何配置 Api接口调用次数

**Comment by iCloudZA** [comment]
新的api系统开发中 这个版本不在维护，感谢您的支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月17日(周五) 晚上10:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [iCloudZA/CloudZA_API] 如何配置 Api接口调用次数 (Issue #7)




 
如何配置 Api接口调用次数

**Comment by kxzjoker** [comment]
大佬，能说一下怎么配置吗，我比较小白，并且我觉得现在这个系统挺好用的。

**Comment by iCloudZA** [comment]
加我微信17520114609



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月17日(周五) 晚上11:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [iCloudZA/CloudZA_API] 如何配置 Api接口调用次数 (Issue #7)




 
大佬，能说一下怎么配置吗，我比较小白，并且我觉得现在这个系统挺好用的。
